spring.application.name=vogle
spring.profiles.active=${ACTIVE_PROFILE:dev}
deepl.api.key=${DEEPL_API_KEY}

# ===============================
# DATABASE - SUPABASE POSTGRESQL
# ===============================

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DATABASE}?sslmode=require}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD:${DB_USER_PASSWORD:}}
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}
spring.flyway.locations=classpath:db/migration

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER
# ===============================

server.port=8080

# ===============================
# FLYWAY
# ===============================

spring.flyway.enabled=true
